name: Python Package Testing

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests with python 3.12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pip install pytest pytest-cov
          pytest --junit-xml=result.xml --cov=your_package_name
  tests with python 3.13:
    runs-on: ubuntu-latest
    needs: tests with python 3.12
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pip install pytest pytest-cov
          pytest --junit-xml=result.xml --cov=your_package_name